"""add workers trade events and audit logs

Revision ID: dbadfc1c9d03
Revises: 21e55eef1d53
Create Date: 2026-05-02 16:15:00.802985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dbadfc1c9d03'
down_revision: Union[str, Sequence[str], None] = '21e55eef1d53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_type', sa.String(length=50), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('payload_json', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=100), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['trading_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_account_id'), 'audit_logs', ['account_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_type'), 'audit_logs', ['actor_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_table('workers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('machine_name', sa.String(length=255), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('last_error_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['trading_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workers_account_id'), 'workers', ['account_id'], unique=False)
    op.create_index(op.f('ix_workers_status'), 'workers', ['status'], unique=False)
    op.create_table('trade_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trade_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('event_message', sa.Text(), nullable=True),
    sa.Column('payload_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_events_event_type'), 'trade_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_trade_events_trade_id'), 'trade_events', ['trade_id'], unique=False)
    op.add_column('signal_logs', sa.Column('trend_bias', sa.String(length=20), nullable=True))
    op.add_column('signal_logs', sa.Column('liquidity_sweep_detected', sa.Boolean(), nullable=False))
    op.add_column('signal_logs', sa.Column('bos_detected', sa.Boolean(), nullable=False))
    op.add_column('signal_logs', sa.Column('entry_price', sa.Numeric(precision=18, scale=6), nullable=True))
    op.add_column('signal_logs', sa.Column('stop_loss', sa.Numeric(precision=18, scale=6), nullable=True))
    op.add_column('signal_logs', sa.Column('take_profit', sa.Numeric(precision=18, scale=6), nullable=True))
    op.alter_column('signal_logs', 'timeframe',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('signal_logs', 'direction',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.drop_column('signal_logs', 'signal_type')
    op.drop_column('signal_logs', 'payload')
    op.add_column('trades', sa.Column('signal_id', sa.Integer(), nullable=True))
    op.add_column('trades', sa.Column('external_ticket', sa.String(length=100), nullable=True))
    op.add_column('trades', sa.Column('direction', sa.String(length=20), nullable=False))
    op.add_column('trades', sa.Column('closed_price', sa.Numeric(precision=18, scale=6), nullable=True))
    op.add_column('trades', sa.Column('rr_realized', sa.Numeric(precision=10, scale=4), nullable=True))
    op.add_column('trades', sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('trades', sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('trades', 'lot_size',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               type_=sa.Numeric(precision=12, scale=4),
               existing_nullable=False)
    op.alter_column('trades', 'entry_price',
               existing_type=sa.NUMERIC(precision=12, scale=4),
               type_=sa.Numeric(precision=18, scale=6),
               existing_nullable=False)
    op.alter_column('trades', 'stop_loss',
               existing_type=sa.NUMERIC(precision=12, scale=4),
               type_=sa.Numeric(precision=18, scale=6),
               nullable=True)
    op.alter_column('trades', 'take_profit',
               existing_type=sa.NUMERIC(precision=12, scale=4),
               type_=sa.Numeric(precision=18, scale=6),
               nullable=True)
    op.alter_column('trades', 'pnl',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Numeric(precision=18, scale=6),
               existing_nullable=True)
    op.create_foreign_key(None, 'trades', 'signal_logs', ['signal_id'], ['id'])
    op.drop_column('trades', 'side')
    op.drop_column('trades', 'close_price')
    op.drop_column('trades', 'mt5_ticket')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('mt5_ticket', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('trades', sa.Column('close_price', sa.NUMERIC(precision=12, scale=4), autoincrement=False, nullable=True))
    op.add_column('trades', sa.Column('side', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'trades', type_='foreignkey')
    op.alter_column('trades', 'pnl',
               existing_type=sa.Numeric(precision=18, scale=6),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=True)
    op.alter_column('trades', 'take_profit',
               existing_type=sa.Numeric(precision=18, scale=6),
               type_=sa.NUMERIC(precision=12, scale=4),
               nullable=False)
    op.alter_column('trades', 'stop_loss',
               existing_type=sa.Numeric(precision=18, scale=6),
               type_=sa.NUMERIC(precision=12, scale=4),
               nullable=False)
    op.alter_column('trades', 'entry_price',
               existing_type=sa.Numeric(precision=18, scale=6),
               type_=sa.NUMERIC(precision=12, scale=4),
               existing_nullable=False)
    op.alter_column('trades', 'lot_size',
               existing_type=sa.Numeric(precision=12, scale=4),
               type_=sa.NUMERIC(precision=10, scale=4),
               existing_nullable=False)
    op.drop_column('trades', 'closed_at')
    op.drop_column('trades', 'opened_at')
    op.drop_column('trades', 'rr_realized')
    op.drop_column('trades', 'closed_price')
    op.drop_column('trades', 'direction')
    op.drop_column('trades', 'external_ticket')
    op.drop_column('trades', 'signal_id')
    op.add_column('signal_logs', sa.Column('payload', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('signal_logs', sa.Column('signal_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.alter_column('signal_logs', 'direction',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.alter_column('signal_logs', 'timeframe',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.drop_column('signal_logs', 'take_profit')
    op.drop_column('signal_logs', 'stop_loss')
    op.drop_column('signal_logs', 'entry_price')
    op.drop_column('signal_logs', 'bos_detected')
    op.drop_column('signal_logs', 'liquidity_sweep_detected')
    op.drop_column('signal_logs', 'trend_bias')
    op.drop_index(op.f('ix_trade_events_trade_id'), table_name='trade_events')
    op.drop_index(op.f('ix_trade_events_event_type'), table_name='trade_events')
    op.drop_table('trade_events')
    op.drop_index(op.f('ix_workers_status'), table_name='workers')
    op.drop_index(op.f('ix_workers_account_id'), table_name='workers')
    op.drop_table('workers')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_account_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
